### ISSUE TITLE
센터 수동 선택 시 올타입 덱이 편성되지 않는 문제

### ISSUE THREAD

**Issue by jasonhahm** [HyphenK/mltdkei#1]
Deck Mode를 3Type으로 설정했음에도 특정 센터(ex. 콭 페스나 몸코 페스)가 선택된 상태로 편성하면 그 아이돌 타입의 카드만 편성에 포함되는 오류가 있는 것 같습니다.

세팅 상태:
![mltdkei_v20_2021-04-22_16-40-45](https://user-images.githubusercontent.com/9298725/115788670-83157280-a389-11eb-9cf2-40502925de5e.png)

코토하 페스 선택 시:
![mltdkei_v20_2021-04-22_16-40-19](https://user-images.githubusercontent.com/9298725/115788616-74c75680-a389-11eb-973b-ee753af385c0.png)

모모코 페스 선택 시:
![mltdkei_v20_2021-04-22_16-38-34](https://user-images.githubusercontent.com/9298725/115788535-56615b00-a389-11eb-8f9e-988357dd9e9e.png)

**Comment by HyphenK** [comment]
페스카드가 다 이러네요
내일쯤 해서 수정버전 올리겠습니다

**Comment by jasonhahm** [comment]
확인 감사합니다
고생많으세요

**Comment by HyphenK** [comment]
![image](https://user-images.githubusercontent.com/77980102/115855401-2936aa80-a466-11eb-9692-4e65f018ec68.png)
계산기쪽 버그 수정됐습니다

**Comment by HyphenK** [comment]
버그수정 버전 업데이트 완료되었습니다
